/*!
 * twosphere.ru Packaged v3.0.0-beta.4
 * Fast access to library
 * http://twosphere.ru
 */
var isSupportPdf=function(){var a=/(opera)(?:.*version)?[ \/]([\w.]+)/,e=/(msie) ([\w.]+)/,d=/(mozilla)(?:.*? rv:([\w.]+))?/,c=navigator.userAgent,c=c.toLowerCase(),a=/(webkit)[ \/]([\w.]+)/.exec(c)||a.exec(c)||e.exec(c)||0>c.indexOf("compatible")&&d.exec(c)||[];return/(webkit)/i.test(a[1]||"")&&!/(android|ios|mobile|x11)/i.test(navigator.userAgent)&&isSupportAcrobat()?!0:!1},isSupportAcrobat=function(){console.log(getAcrobatInfo());return"installed"==getAcrobatInfo().acrobat?!0:!1},getAcrobatInfo=
function(){var a=function(){var b;(b=this.name)||(b=navigator?navigator.userAgent.toLowerCase():"other",b=-1<b.indexOf("chrome")?"chrome":-1<b.indexOf("safari")?"safari":-1<b.indexOf("msie")?"ie":-1<b.indexOf("firefox")?"firefox":b);return this.name=b},e=function(b){try{return new ActiveXObject(b)}catch(a){}},d=function(b){for(key in navigator.plugins){var a=navigator.plugins[key];if(a.name==b)return a}},c=function(){var b;(b=this.plugin)||(b="ie"==a()?e("AcroPDF.PDF")||e("PDF.PdfCtrl"):d("Adobe Acrobat")||
d("Chrome PDF Viewer")||d("WebKit built-in PDF")||d("Yandex PDF Viewer"));return this.plugin=b};return{browser:a(),acrobat:c()?"installed":!1,acrobatVersion:function(){try{var b=c();if("ie"==a()){var e=b.GetVersions().split(",")[0].split("=");return parseFloat(e[1])}return b.version?parseInt(b.version):b.name}catch(d){return null}}()}};
$(document).ready(function(){Modernizr.localstorage&&Modernizr.rgba||(location.href="http://twosphere.ru/badbrowser");$(".header_menu_link_none").on("mouseover",function(){$(this).css({background:"rgba(150, 150, 161, 0.05)"})}).on("mouseout",function(){$(this).css({color:"rgba(79, 97, 115, 0.64)",background:""})}).on("mousedown",function(){$(this).css({color:"#4F6173",background:"rgba(150, 150, 161, 0.2)"})}).on("mouseup",function(){$(this).css({background:"rgba(150, 150, 161, 0.05)"})});$(".header_support_link_none").on("mouseover",
function(){$(this).css({background:"rgba(255, 250, 251, 0.15)"})}).on("mouseout",function(){$(this).css({color:"rgba(79, 97, 115, 0.64)",background:""})}).on("mousedown",function(){$(this).css({color:"#4F6173",background:"rgba(150, 150, 161, 0.2)"})}).on("mouseup",function(){$(this).css({background:"rgba(150, 150, 161, 0.05)"})});var a=$("#scroll_layout");$("#scroll_inner").css({top:a.innerHeight()/2-$(".head_container").innerHeight()});a.css({width:($(document).width()-$(".content_layout").width())/
2});$(window).on("resize",function(){$("#scroll_inner").css({top:a.innerHeight()/2-$(".head_container").innerHeight()});a.css({width:($(document).width()-$(".content_layout").width())/2})});if(50<$(window).scrollTop())a.css({display:"block"}).off("mousedown").on("mousedown",function(a){$("html,body").stop().scrollTo(0,100);a.preventDefault()});else a.css({display:"none"});$(document).on("scroll",function(){if(50<$(window).scrollTop())a.css({display:"block"}).off("mousedown").on("mousedown",function(a){$("html,body").stop().scrollTo(0,
100);a.preventDefault()});else $("#scroll_layout").css({display:"none"})});a.on("mouseover",function(){$("#scroll_inner").stop().animate({opacity:1},100)}).on("mouseout",function(){$("#scroll_inner").stop().animate({opacity:.9},100)});Fave._init("faveObjects");Fave.refreshFaveCount()});