/*!
 * twosphere.ru Packaged v3.0.0-alpha.4
 * Fast access to library
 * http://twosphere.ru
 */
$(document).ready(function(){$.cookie&&1!=$.cookie("img_notify")?$("#notify_image_layer")&&setTimeout(function(){$("#notify_image_layer").animate({top:"0px",left:"0px",opacity:1},300,function(){$.cookie("img_notify","1",{expires:1E4,path:"/"});$(".notify_message").css({position:"static"})})},300):($("#notify_image_layer")&&$("#notify_image_layer").css({top:"0px",left:"0px",opacity:1}),$(".notify_message")&&$(".notify_message").css({position:"static"}));$(".notify_close")&&$(".notify_close").on("click",
function(){$("#fl_notification_message").animate({opacity:0,marginTop:"-=200",marginBottom:"-=30"},100,function(){$.cookie("notify_s","1",{expires:1E4,path:"/"});$("#fl_notification_message").remove()})});var b,c=function(){var a=$(".search_advice");a&&"none"==a.css("display")&&(a.css({opacity:0,marginTop:"15px",display:"block"}),a.stop(!0,!0).animate({opacity:1,marginTop:"-=10"},100,function(){b=setTimeout(function(){a.animate({opacity:0,marginTop:"+=10"},200,function(){a.css({display:"none"})})},
4E3)}))};$("#input_text").on("click",c).on("focus",c).on("blur",function(){var a=$(".search_advice");a&&"block"==a.css("display")&&(clearTimeout(b),a.css({opacity:1,marginTop:"5px"}),a.stop(!0,!0).animate({opacity:0,marginTop:"+=10"},100,function(){a.css({display:"none"})}))});$("#sp_select_category")&&$("#sp_select_category").styler().on("change",function(){Search.setCategory(this.value)});Search.setIntervalSearch(100);c=document.getElementById("search_loading");(new Spinner({lines:5,length:0,width:7,
radius:7,corners:1,rotate:53,direction:1,color:"#AAA",speed:2.2,trail:10,shadow:!1,hwaccel:!1,className:"spinner",zIndex:2E4,top:"0",left:"0"})).spin(c);$(".search_load_spin").on("click",function(){$("#input_text").focus()});Page.getPopular();Search.setCategory(document.getElementById("sp_select_category").value);/*$("#input_text").on("keyup",function(a){0!=Search.previous_value.length&&13==a.keyCode&&(a=$(".search_result_wrap:first")[0].getElementsByTagName("a")[0])&&a.click()}).focus();*/});
$(document).ready(function(){var b=$(".pdf_wrapper"),c=$("html,body").innerHeight();b.css({height:c-60+"px"});$(window).resize(function(){var a=$(".pdf_wrapper"),b=$("html,body").innerHeight();a.css({height:b-60+"px"})});isSupportPdf()&&($("<div class='pdf_view_back_layer' style='opacity: 0;' onclick='PdfViewer.close()'><div class='pdf_view_back'><div class='pdf_view_back_icon'></div><span>\u0412\u0435\u0440\u043d\u0443\u0442\u044c\u0441\u044f \u043a \u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u0443 \u043f\u043e\u0438\u0441\u043a\u0430</span></div></div>").insertAfter(".nav"),
b=decodeURIComponent(window.location).replace(/(%3A)/g,":").replace(/(%2F)/g,"/").replace(/(%3F)/g,"?").replace(/(%3D)/g,"="),/(open)/i.test(window.location)&&/^http:\/\/twosphere\.ru\/\?open\=[a-zA-Z0-9]{16,}/i.test(b)&&(b=window.location.toString().match(/open\=(.*)[&]*/i)[1],PdfViewer.open(decodeURIComponent(b))))});
var PdfViewer={open:function(b){$(".pdf_view_back_layer").css({top:"0px",opacity:1});var c=$(".pdf_layer")[0].childNodes[0];c&&c.remove();c=document.createElement("iframe");c.src="http://twosphere.ru/doc/?id=" + decodeURIComponent(b);c.height="100%";c.width="100%";c.style.border="0";setTimeout(function(){$(".pdf_layer").append(c)},200);var a=document.getElementById("pdf_wrapper");$(a).css({display:"block"}).animate({top:"60px"},200);window.history.pushState&&window.history.pushState(null,null,"?open="+encodeURIComponent(b))},close:function(){var b=
$(".pdf_layer")[0].childNodes[0];b&&b.remove();b=document.getElementById("pdf_wrapper");$(b).animate({top:$("html,body").innerHeight()+100+"px"},200,function(){$(this).css({display:"none"})});$(".pdf_view_back_layer").css({top:"-100px",opacity:0});window.history.pushState&&window.history.pushState(null,null,"/")}};

$(document).ready(function() {
    $("#donate").css({width:1100}).oModal({top:50,marginBottom:50,closeButton:".popup_close,.popup_cancel"});
});